### ISSUE TITLE
BrowserModule error in lazy loaded modules

### ISSUE THREAD

**Issue by sainttyraell** [openopus/ng-pane-manager2#1]
Impossible to Import AngularPaneManagerModule in lazy loaded part of application. Getting error: 

"_ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead._"

Error does not occur if i'm importing and using AngularPaneManagerModule directly in app.component.ts 

Angular version: **9.1.12**

**Comment by rookie1024** [comment]
Do you have a minimal example or steps to reproduce?

It’s possible this is a peer dependency mismatch issue, as the latest version of angular-pane-manager was tested against Angular 10.

**Comment by sainttyraell** [comment]
If its not a problem for you please take a look on my modification of your example at https://github.com/sainttyraell/ng-pane-manager2/blob/master/examples/04-dynamic-layout/src/app/app.routing.module.ts

**Comment by rookie1024** [comment]
Ah, I see the problem.  Let me verify that the tests pass and I can push a fix.

**Comment by rookie1024** [comment]
Pushed an update with the fix and another pending commit.  Does this solve your problem @sainttyraell?

**Comment by sainttyraell** [comment]
@rookie1024 works like a charm! Thank you for fix, appreciate it. Btw, u did great job with this library.
